apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: groups.nextcluster.net
spec:
  group: nextcluster.net
  scope: Namespaced
  names:
    kind: Group
    singular: group
    plural: groups
    shortNames:
      - ng
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                base:
                  type: object
                  properties:
                    image:
                      type: string
                    ports:
                      type: array
                      default: []
                      items:
                        type: object
                        properties:
                          name:
                            type: string
                            default: null
                          port:
                            type: integer
                          expose:
                            type: integer
                            default: null
                          protocol:
                            type: string
                            default: TCP
                    volumes:
                      type: array
                      default: []
                      items:
                        type: object
                        properties:
                          name:
                            type: string
                          host:
                            type: string
                          container:
                            type: string
                    environment:
                      type: array
                      default: []
                      items:
                        type: string
                    imagePullSecrets:
                      type: array
                      default: []
                      items:
                        type: string
                maintenance:
                  type: boolean
                  default: false
                fallback:
                  type: boolean
                  default: false
                preferredFallback:
                  type: string
                  default: ''
                minOnline:
                  type: integer
                  default: 1
                maxOnline:
                  type: number
                  default: 1000
                maxMemory:
                  type: number
                static:
                  type: boolean
                  default: false
            status:
              type: object
              properties:
                players:
                  type: number
                memory:
                  type: number
